package com.bogliaccino.canzoni.services;

import java.util.ArrayList;
import java.util.List;

public class DBCantanti {

	private static List<String[]> canzoni = new ArrayList<>();
	
	public static List<String[]> getCanzoni(){
		
		canzoni.clear();
		
		canzoni.add(new String[]{"Titolo - Interprete",""});
		canzoni.add(new String[]{"Malibù "," Sangiovanni"});
		canzoni.add(new String[]{"Mi fai impazzire "," Blanco & Sfera Ebbasta"});
		canzoni.add(new String[]{"Mille "," Fedez & Achille Lauro & Orietta Berti"});
		canzoni.add(new String[]{"La canzone nostra "," Mace & Blanco & Salmo"});
		canzoni.add(new String[]{"Musica leggerissima "," Colapesce & Dimartino"});
		canzoni.add(new String[]{"Zitti e buoni "," Maneskin"});
		canzoni.add(new String[]{"Lady "," Sangiovanni"});
		canzoni.add(new String[]{"Stay "," The Kid Laroi & Justin Bieber"});
		canzoni.add(new String[]{"Bad habits "," Ed Sheeran"});
		canzoni.add(new String[]{"Notti in bianco "," Blanco"});
		canzoni.add(new String[]{"Un bacio all'improvviso "," Rocco Hunt & Ana Mena"});
		canzoni.add(new String[]{"Ma stasera "," Marco Mengoni"});
		canzoni.add(new String[]{"Ti raggiungerò "," Fred De Palma"});
		canzoni.add(new String[]{"Friday [dopamine reedit] "," Riton & Nightcrawlers feat. Mufasa & Hypeman"});
		canzoni.add(new String[]{"Venere e Marte "," Takagi e Ketra & Marco Mengoni & Frah Quintale"});
		canzoni.add(new String[]{"Movimento lento "," Annalisa feat. Federico Rossi"});
		canzoni.add(new String[]{"Makumba "," Noemi & Carl Brave"});
		canzoni.add(new String[]{"Cold heart [pnau remix] "," Elton John & Dua Lipa"});
		canzoni.add(new String[]{"Never going home "," Kungs"});
		canzoni.add(new String[]{"Marea "," Madame"});
		canzoni.add(new String[]{"Save your tears "," The Weeknd"});
		canzoni.add(new String[]{"Voce "," Madame"});
		canzoni.add(new String[]{"Nuovo range "," Rkomi & Sfera Ebbasta & Junior K"});
		canzoni.add(new String[]{"La genesi del tuo colore "," Irama"});
		canzoni.add(new String[]{"Scrivile scemo "," Pinguini Tattici Nucleari"});
		canzoni.add(new String[]{"I wanna be your slave "," Maneskin"});
		canzoni.add(new String[]{"Tu mi hai capito "," Madame & Sfera Ebbasta"});
		canzoni.add(new String[]{"Pepas "," Farruko"});
		canzoni.add(new String[]{"Mohicani "," BoomDaBash & Baby K"});
		canzoni.add(new String[]{"Partire da te "," Rkomi"});
		canzoni.add(new String[]{"Ferma a guardare "," Ernia feat. Pinguini Tattici Nucleari"});
		canzoni.add(new String[]{"Una canzone d'amore buttata via "," Vasco Rossi"});
		canzoni.add(new String[]{"Chiamami per nome "," Francesca Michielin & Fedez"});
		canzoni.add(new String[]{"Loca "," Aka 7even"});
		canzoni.add(new String[]{"Iko iko "," Justin Wellington feat. Small Jam"});
		canzoni.add(new String[]{"Your love (9 PM) "," ATB & Topic & A7S"});
		canzoni.add(new String[]{"Luna piena "," Rkomi & Irama & Shablo"});
		canzoni.add(new String[]{"Pastello bianco "," Pinguini Tattici Nucleari"});
		canzoni.add(new String[]{"Paraocchi "," Blanco"});
		canzoni.add(new String[]{"Pistolero "," Elettra Lamborghini"});
		canzoni.add(new String[]{"Scooby Doo "," Pinguini Tattici Nucleari"});
		canzoni.add(new String[]{"Fireworks "," Purple Disco Machine feat. Moss Kena & Knocks"});
		canzoni.add(new String[]{"Peaches "," Justin Bieber feat. Daniel Caesar & Giveon"});
		canzoni.add(new String[]{"Baby "," Sfera Ebbasta & J Balvin"});
		canzoni.add(new String[]{"Blu celeste "," Blanco"});
		canzoni.add(new String[]{"Un altro ballo "," Fred De Palma feat. Anitta"});
		canzoni.add(new String[]{"Salsa ","J-Ax & Jake La Furia"});
		canzoni.add(new String[]{"Kumite "," Salmo"});
		canzoni.add(new String[]{"Don't go yet "," Camila Cabello"});
		canzoni.add(new String[]{"Shimmy Shimmy "," Takagi & Ketra & Giusy Ferreri"});
		canzoni.add(new String[]{"A un passo dalla luna "," Rocco Hunt & Ana Mena"});
		canzoni.add(new String[]{"Mi manchi "," Aka 7even"});
		canzoni.add(new String[]{"Paradise "," Meduza feat. Dermot Kennedy"});
		canzoni.add(new String[]{"We are the people "," Martin Garrix feat. Bono & the Edge"});
		canzoni.add(new String[]{"Run "," OneRepublic"});
		canzoni.add(new String[]{"Love tonight "," Shouse"});
		canzoni.add(new String[]{"Higher power "," Coldplay"});
		canzoni.add(new String[]{"Shivers "," Ed Sheeran"});
		canzoni.add(new String[]{"Dieci "," Annalisa"});
		canzoni.add(new String[]{"Meglio del cinema "," Fedez"});
		canzoni.add(new String[]{"Easy on me "," Adele"});
		canzoni.add(new String[]{"Fiamme negli occhi "," Coma_Cose"});
		canzoni.add(new String[]{"Melodia proibita "," Irama"});
		canzoni.add(new String[]{"uNa DiReZioNe giUsTa "," Yungest Moonstar & Neffa & tha Supreme"});
		canzoni.add(new String[]{"My universe "," Coldplay & BTS"});
		canzoni.add(new String[]{"Beggin "," Maneskin"});
		canzoni.add(new String[]{"Take my breath "," The Weeknd"});
		canzoni.add(new String[]{"Vertigine "," Elodie"});
		canzoni.add(new String[]{"Destri "," Gazzelle"});
		canzoni.add(new String[]{"Bed "," Joel Corry & Raye & David Guetta"});
		canzoni.add(new String[]{"Superclassico "," Ernia"});
		canzoni.add(new String[]{"Pezzo di cuore "," Emma & Alessandra Amoroso"});
		canzoni.add(new String[]{"Rubini "," Mahmood & Elisa"});
		canzoni.add(new String[]{"Inuyasha "," Mahmood"});
		canzoni.add(new String[]{"Bongo cha cha cha "," Goodboys"});
		canzoni.add(new String[]{"Afterglow "," Ed Sheeran"});
		canzoni.add(new String[]{"Follow you "," Imagine Dragons"});
		canzoni.add(new String[]{"Magari no "," Tommaso Paradiso"});
		canzoni.add(new String[]{"Dopamine "," Purple Disco Machine feat. Eyelar"});
		canzoni.add(new String[]{"Love again "," Dua Lipa"});
		canzoni.add(new String[]{"Leave the door open "," Bruno Mars & Anderson .Paak & Silk Sonic"});
		canzoni.add(new String[]{"0 passi "," Deddy"});
		canzoni.add(new String[]{"Montero (Call me by your name) "," Lil Nas X"});
		canzoni.add(new String[]{"L'ultima notte "," Ariete"});
		canzoni.add(new String[]{"We could be dancing "," Bob Sinclar feat. Molly Hammar"});
		canzoni.add(new String[]{"Beautiful mistakes "," Maroon 5 & Megan Thee Stallion"});
		canzoni.add(new String[]{"Glicine "," Noemi"});
		canzoni.add(new String[]{"Drivers license "," Olivia Rodrigo"});
		canzoni.add(new String[]{"Tutta la notte "," Sangiovanni"});
		canzoni.add(new String[]{"Vent'anni "," Maneskin"});
		canzoni.add(new String[]{"Las Vegas "," Tancredi"});
		canzoni.add(new String[]{"Hecha pa' mí "," Boza"});
		canzoni.add(new String[]{"Cinema "," Samuel & Francesca Michielin"});
		canzoni.add(new String[]{"Amare "," La Rappresentante Di Lista"});
		canzoni.add(new String[]{"Don't worry "," BoomDaBash"});
		canzoni.add(new String[]{"Yo no sè "," Rvfv"});
		canzoni.add(new String[]{"Industry baby "," Lil Nas X & Jack Harlow"});
		canzoni.add(new String[]{"Il mio amico "," Madame & Fabri Fibra"});
		canzoni.add(new String[]{"Non fare così "," Capo Plaza"});
		canzoni.add(new String[]{"Sorriso grande "," Alessandra Amoroso"});
		canzoni.add(new String[]{"Crazy love","Marracash"});
		canzoni.add(new String[]{"Pastello bianco","Pinguini Tattici Nucleari"});
		canzoni.add(new String[]{"Easy on me","Adele"});
		canzoni.add(new String[]{"? Love","Marracash & Guè Pequeno"});
		canzoni.add(new String[]{"Cold heart [pnau remix]","Elton John & Dua Lipa"});
		canzoni.add(new String[]{"Come nelle canzoni","Coez"});
		canzoni.add(new String[]{"Sapore","Fedez feat. Tedua"});
		canzoni.add(new String[]{"Pepas","Farruko"});
		canzoni.add(new String[]{"Vertigine","Elodie"});
		canzoni.add(new String[]{"La più bella","Mecna & CoCo"});
		canzoni.add(new String[]{"Kumite","Salmo"});
		canzoni.add(new String[]{"My universe","Coldplay & BTS"});
		canzoni.add(new String[]{"Cambia un uomo","Marco Mengoni"});
		canzoni.add(new String[]{"Siamo qui","Vasco Rossi"});
		canzoni.add(new String[]{"Finchè non mi seppelliscono","Blanco"});
		canzoni.add(new String[]{"Perso nel buio","Sangiovanni & Madame"});
		canzoni.add(new String[]{"Shivers","Ed Sheeran"});
		canzoni.add(new String[]{"Mi fai impazzire","Blanco & Sfera Ebbasta"});
		canzoni.add(new String[]{"Nemesi","Marracash & Blanco"});
		canzoni.add(new String[]{"Wallah","Ghali"});
		canzoni.add(new String[]{"Mi piace","Tony Effe & Sfera Ebbasta"});
		canzoni.add(new String[]{"Dopamine","Purple Disco Machine feat. Eyelar"});
		canzoni.add(new String[]{"Tu mi hai capito","Madame & Sfera Ebbasta"});
		canzoni.add(new String[]{"Io","Marracash"});
		canzoni.add(new String[]{"Lipstick","Kungs"});
		canzoni.add(new String[]{"Overpass graffiti","Ed Sheeran"});
		canzoni.add(new String[]{"Dubbi","Marracash"});
		canzoni.add(new String[]{"Moth to a flame","Swedish House Mafia & The Weeknd"});
		canzoni.add(new String[]{"Golden nights","Sophie and The Giants feat. Benny Benassi & Dardust & Astrality"});
		canzoni.add(new String[]{"Stay","The Kid Laroi & Justin Bieber"});
		canzoni.add(new String[]{"Thats what I want","Lil Nas X"});
		canzoni.add(new String[]{"Loro","Marracash"});
		canzoni.add(new String[]{"Seta","Elisa"});
		canzoni.add(new String[]{"Magari no","Tommaso Paradiso"});
		canzoni.add(new String[]{"Do it to it","Acraze feat. Cherish"});
		canzoni.add(new String[]{"Mammamia","Maneskin"});
		canzoni.add(new String[]{"Notti in bianco","Blanco"});
		canzoni.add(new String[]{"Blu celeste","Blanco"});
		canzoni.add(new String[]{"Niente","Ultimo"});
		canzoni.add(new String[]{"Meglio del cinema","Fedez"});
		canzoni.add(new String[]{"abcdefu","Gayle"});
		canzoni.add(new String[]{"All I want for Christmas is you","Mariah Carey"});
		canzoni.add(new String[]{"Il boom","Jovanotti"});
		canzoni.add(new String[]{"Laurea Ad Honorem","Marracash & Calcutta"});
		canzoni.add(new String[]{"Pagliaccio","Marracash"});
		canzoni.add(new String[]{"Quello che fa male","LDA"});
		canzoni.add(new String[]{"Mille","Fedez & Achille Lauro & Orietta Berti"});
		canzoni.add(new String[]{"Canzone inutile","Alessandra Amoroso"});
		canzoni.add(new String[]{"Noi","Marracash"});
		canzoni.add(new String[]{"Malibù","Sangiovanni"});
		canzoni.add(new String[]{"Rubini","Mahmood & Elisa"});
		canzoni.add(new String[]{"Cosplayer","Marracash"});
		canzoni.add(new String[]{"Don't go yet","Camila Cabello"});
		canzoni.add(new String[]{"Smokin out the window","Bruno Mars & Anderson .Paak & Silk Sonic"});
		canzoni.add(new String[]{"Someday","OneRepublic"});
		canzoni.add(new String[]{"Industry baby","Lil Nas X & Jack Harlow"});
		canzoni.add(new String[]{"Bad habits","Ed Sheeran"});
		canzoni.add(new String[]{"Scrivile scemo","Pinguini Tattici Nucleari"});
		canzoni.add(new String[]{"Niente è andato perso","Mina & Adriano Celentano"});
		canzoni.add(new String[]{"Gli altri (Giorni stupidi)","Marracash"});
		canzoni.add(new String[]{"Your song saved my life","U2"});
		canzoni.add(new String[]{"Fantastica","Rocco Hunt & Boomdabash"});
		canzoni.add(new String[]{"Paraocchi","Blanco"});
		canzoni.add(new String[]{"Luna piena","Rkomi & Irama & Shablo"});
		canzoni.add(new String[]{"Nuvole di zanzare","Gaia"});
		canzoni.add(new String[]{"Nuovo range","Rkomi & Sfera Ebbasta & Junior K"});
		canzoni.add(new String[]{"Cliffhanger","Marracash"});
		canzoni.add(new String[]{"La cassa spinge 2021","Fedez feat. Crookers & M¥SS KETA & Dargen D'Amico"});
		canzoni.add(new String[]{"Spazio tempo","Francesco Gabbani"});
		canzoni.add(new String[]{"uNa DiReZioNe giUsTa","Yungest Moonstar & Neffa & tha Supreme"});
		canzoni.add(new String[]{"Beggin","Maneskin"});
		canzoni.add(new String[]{"Zitti e buoni","Maneskin"});
		canzoni.add(new String[]{"Partire da te","Rkomi"});
		canzoni.add(new String[]{"Un bacio all'improvviso","Rocco Hunt & Ana Mena"});
		canzoni.add(new String[]{"Tell it to my heart","Meduza feat. Hozier"});
		canzoni.add(new String[]{"Ora ti canto il mare","Negramaro"});
		canzoni.add(new String[]{"I wanna be your slave","Maneskin"});
		canzoni.add(new String[]{"Guardare giù","Noemi"});
		canzoni.add(new String[]{"Heat waves","Glass Animals"});
		canzoni.add(new String[]{"m%n","tha Supreme"});
		canzoni.add(new String[]{"Un giorno in pretura","Fedez"});
		canzoni.add(new String[]{"Lucciole","Blanco"});
		canzoni.add(new String[]{"Last Christmas","Wham!"});
		canzoni.add(new String[]{"Stupido stupido","Fedez"});
		canzoni.add(new String[]{"Quanto ti vorrei","Chiello & Shablo"});
		canzoni.add(new String[]{"Angelina Jolie","Bresh"});
		canzoni.add(new String[]{"Ma stasera","Marco Mengoni"});
		canzoni.add(new String[]{"Vittoria","Fedez"});
		canzoni.add(new String[]{"Love nwantiti (Ah ah ah) [remix]","CKay feat. Joeboy & Kuami Eugene"});
		canzoni.add(new String[]{"Ready","SLF & MV Killa & Yung Snapp feat. Lele Blade & Vale Lambo & Geolier"});
		canzoni.add(new String[]{"Movimento lento","Annalisa feat. Federico Rossi"});
		canzoni.add(new String[]{"Love nwantiti [north african remix]","CKay feat. ElGrande Toto"});
		canzoni.add(new String[]{"Millevoci","Albè"});
		canzoni.add(new String[]{"Angels","LP"});
		canzoni.add(new String[]{"Pudini #2","Philip feat. Simba La Rue"});
		canzoni.add(new String[]{"Triste","Sfera Ebbasta & Feid"});
		canzoni.add(new String[]{"Enemy","Imagine Dragons & JID & League of Legends"});
		canzoni.add(new String[]{"Opinel","Simba La Rue"});
		canzoni.add(new String[]{"Uhlala","Sfera Ebbasta"});
		canzoni.add(new String[]{"Noi, loro, gli altri skit","Marracash"});
		canzoni.add(new String[]{"Colpevole RMX","Tony Effe feat. Geolier"});
		canzoni.add(new String[]{"Ghost","Justin Bieber"});
		canzoni.add(new String[]{"Come, come","Sissi"});
		canzoni.add(new String[]{"Don't be shy","Tiesto & Karol G"});
		canzoni.add(new String[]{"Pull up","Mambolosco"});
		canzoni.add(new String[]{"La canzone nostra","Mace & Blanco & Salmo"});
		canzoni.add(new String[]{"Follow you follow me","Zucchero"});
		canzoni.add(new String[]{"Out out","Joel Corry & Jax Jones feat. Charli XCX & Saweetie"});
		canzoni.add(new String[]{"Qualcosa di me che non ti aspetti","Carmen Consoli"});
		canzoni.add(new String[]{"Take 2","Shiva"});
		canzoni.add(new String[]{"Fuori dai guai","Fedez feat. Cara"});
		canzoni.add(new String[]{"Chiamami per nome","Francesca Michielin & Fedez"});
		canzoni.add(new String[]{"Un altro ballo","Fred De Palma feat. Anitta"});
		canzoni.add(new String[]{"Rompo","VillaBanks & Boro Boro"});
		canzoni.add(new String[]{"Bohemian rhapsody","Queen"});
		canzoni.add(new String[]{"Colibrì","Cesare Cremonini"});
		canzoni.add(new String[]{"Fottuta canzone","Gazzelle"});
		canzoni.add(new String[]{"Leoni al sole","The Kolors"});
		canzoni.add(new String[]{"Fa' o' brav'","Rocco Hunt feat. Emis Killa & Yung Snapp & Mv Killa & Lele Bla"});
		canzoni.add(new String[]{"Morire morire","Fedez"});
		canzoni.add(new String[]{"Ridere","Pinguini Tattici Nucleari"});
		canzoni.add(new String[]{"Non dire una parola","Baby K & Alvaro Soler"});
		canzoni.add(new String[]{"Take my breath","The Weeknd"});
		canzoni.add(new String[]{"La fama","Rosalía feat. The Weeknd"});
		canzoni.add(new String[]{"It's beginning to look a lot like Christmas","Michael Bublè"});
		canzoni.add(new String[]{"Bimbi per strada (Children)","Fedez & Robert Miles"});
		canzoni.add(new String[]{"Muro","Luigi Strangis"});
		canzoni.add(new String[]{"Milano non esiste","Ermal Meta"});
		canzoni.add(new String[]{"Bella storia","Fedez"});
		canzoni.add(new String[]{"Aldo ritmo","Salmo"});
		canzoni.add(new String[]{"Guarda cosa mi fai fare","Fedez"});
		canzoni.add(new String[]{"Ferma a guardare","Ernia feat. Pinguini Tattici Nucleari"});
		canzoni.add(new String[]{"Blueface","Disme & Vaz Tè feat. Izi & Tedua"});
		canzoni.add(new String[]{"Woman","Doja Cat"});
		canzoni.add(new String[]{"Lose it all","Room9 & Big Boy"});
		canzoni.add(new String[]{"Love tonight","Shouse"});
		canzoni.add(new String[]{"Sai cosa c'è","Blanco"});
		canzoni.add(new String[]{"Caramba","Baby Gang"});
		canzoni.add(new String[]{"One right now","Post Malone & The Weeknd"});
		canzoni.add(new String[]{"Destri","Gazzelle"});
		canzoni.add(new String[]{"Fede e speranza","Fedez feat. Speranza"});
		canzoni.add(new String[]{"Wrecked","Imagine Dragons"});
		canzoni.add(new String[]{"Scusa","Riki"});
		canzoni.add(new String[]{"Veleno 8","Madman feat. Gemitaiz"});
		canzoni.add(new String[]{"Oh my God","Adele"});
		canzoni.add(new String[]{"Eva+Eva","Annalisa feat. Rose Villain"});
		canzoni.add(new String[]{"Marea","Madame"});
		canzoni.add(new String[]{"CRUDELIA: I nervi","Marracash"});
		canzoni.add(new String[]{"Vecchio","Fedez feat. Dargen D'Amico"});
		canzoni.add(new String[]{"Thunder","Gabry Ponte & Lum!x & Prezioso"});
		canzoni.add(new String[]{"Money","Lisa"});
		canzoni.add(new String[]{"La chiave","Salmo feat. Marracash"});
		canzoni.add(new String[]{"Life goes on","Oliver Tree"});
		canzoni.add(new String[]{"Mi sto sul c***o","Fedez"});
		canzoni.add(new String[]{"Raggi gamma","Sangiovanni"});
		canzoni.add(new String[]{"Rushing water","Sting"});
		canzoni.add(new String[]{"Where are you now","Lost Frequencies & Calum Scott"});
		canzoni.add(new String[]{"Ci sarò","Alfa"});
		canzoni.add(new String[]{"Stupido","Massimo Pericolo & Crookers"});
		canzoni.add(new String[]{"Più di te","Emma Muscat"});
		canzoni.add(new String[]{"Friday [dopamine re-edit]","Riton & Nightcrawlers feat. Mufasa & Hypeman"});
		canzoni.add(new String[]{"Ladro di fiori","Blanco"});
		canzoni.add(new String[]{"Makumba","Noemi & Carl Brave"});
		canzoni.add(new String[]{"Weekend","Mufasa & Hypeman X Dopamine"});
		canzoni.add(new String[]{"Sol y mar","Federico Rossi & Ana Mena"});
		canzoni.add(new String[]{"Infinity","Jaymes Young"});
		canzoni.add(new String[]{"10 Ragazze","Rkomi & Ernia & Mace"});
		canzoni.add(new String[]{"Bollywood","Loredana Bertè"});
		canzoni.add(new String[]{"Jingle bell rock","Bobby Helms & The Anita Kerr Singers"});
		canzoni.add(new String[]{"Chillin'","Madman"});
		canzoni.add(new String[]{"Maria","Niko Pandetta"});
		canzoni.add(new String[]{"Bum bum bum","Niko Pandetta feat. Tempoxso & Janax"});
		canzoni.add(new String[]{"Sogni al cielo","Alex W"});
		canzoni.add(new String[]{"El Sendero","Caparezza feat. Mishel Domenssain"});
		canzoni.add(new String[]{"Superclassico","Ernia"});
		canzoni.add(new String[]{"Chella dint'o lietto","Michele Taurino feat. Anthony"});
		canzoni.add(new String[]{"Drippin' in Milano","Anna"});
		canzoni.add(new String[]{"Ma cherie","Baby Gang feat. Capo Plaza"});
		canzoni.add(new String[]{"Sì 'a cosa cchiù bella","Mr.Hyde feat. Rico Femiano"});
		canzoni.add(new String[]{"Baby","Rondodasosa"});
		canzoni.add(new String[]{"Pornografia (Bianco Paradiso)","Blanco"});
		canzoni.add(new String[]{"Scooby Doo","Pinguini Tattici Nucleari"});
		canzoni.add(new String[]{"The motto","Tiesto & Ava Max"});
		canzoni.add(new String[]{"Bye bye","Samurai Jay & Dani"});
		canzoni.add(new String[]{"Notte brava","Fedez"});
		canzoni.add(new String[]{"Sul finale","Ultimo"});
		canzoni.add(new String[]{"Quel filo che ci unisce","Ultimo"});
		canzoni.add(new String[]{"Skate","Bruno Mars & Anderson .Paak & Silk Sonic"});
		canzoni.add(new String[]{"Le madri degli altri","Fedez & Tananai"});
		canzoni.add(new String[]{"L'urdemo vase","Rocco Hunt"});
		canzoni.add(new String[]{"Perfect","Ed Sheeran"});
		canzoni.add(new String[]{"Mezz'ora di sole","Blanco"});
		canzoni.add(new String[]{"Feliz Navidad","Josè Feliciano"});
		canzoni.add(new String[]{"Loco","Justin Quiles & Chimbala & Zion & Lennox"});
		canzoni.add(new String[]{"Open Bar","Il Pagante"});
		canzoni.add(new String[]{"Blinding lights","The Weeknd"});
		canzoni.add(new String[]{"Never going home","Kungs"});
		canzoni.add(new String[]{"Solo per me","MadMan feat. Massimo Pericolo"});
		canzoni.add(new String[]{"Jingle bells","Michael Bublè feat. Puppini Sisters"});

		return canzoni;
	}
	
	
}
